### ISSUE TITLE
Release publishing broken

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/sarif4k#128]
* this was hidden by #119

```
> Task :publishJvmPublicationToSonatypeRepository FAILED

15 actionable tasks: 7 executed, 8 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishJvmPublicationToSonatypeRepository'.
> Failed to publish publication 'jvm' to repository 'sonatype'
   > Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/io/github/detekt/sarif4k/sarif4k-jvm/0.7.0-SNAPSHOT/sarif4k-jvm-0.7.0-20240628.120230-9.jar'. Received status code 401 from server: Content access is protected by token
```

I have the same problem in my Gradle plugin repository. I've read some news about moving to a new Auth mechanism, but I read it as optional and hoped for a longer grace period. apparently that's not the case.

@cortinico @chao2zhang who has access to Sonatype password? There'll be some secrets setup need changing probably, will know more after I fixed my repo.

**Comment by TWiStErRob** [comment]
Email that alerted about this for reference:

> Dear Maven Central publisher,
> 
> We are making changes to the OSSRH authentication backend. For most users this should be a transparent process, and you should be able to continue to use your existing username and password to connect the Nexus UI. In case you need to update your password, please follow our documentation.
> 
> To configure a publisher’s plugin authentication you would need to update your plugin settings to use a user token instead of the Nexus UI username and password login.
> 
> For more information about publishing to legacy OSSRH please consult our documentation at https://central.sonatype.org/register/legacy/
> 
> Thank you,
> The Central Team

The process was quite simple:
1. Log in to https://oss.sonatype.org (based on [our usage of `sonatype()`](https://github.com/detekt/sarif4k/blob/main/build.gradle.kts#L110))
2. Follow https://central.sonatype.org/publish/generate-token/
3. Instead of step 5, replace [`MAVEN_CENTRAL_USER` and `MAVEN_CENTRAL_PW` secrets](https://github.com/detekt/sarif4k/blob/main/.github/workflows/release.yml#L35-L37) at https://github.com/detekt/sarif4k/settings/secrets/actions

**Comment by cortinico** [comment]
Thanks for flagging @TWiStErRob fix is here https://github.com/detekt/sarif4k/pull/129

**Comment by TWiStErRob** [comment]
Confirmed fixed https://github.com/detekt/sarif4k/actions/runs/9809610373/job/27087934526

**Comment by chao2zhang** [comment]
@BraisGabin asked me about getting `./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository` to work with the right credentials. The steps above from @TWiStErRob seems extreme clear.
