### ISSUE TITLE
Publishing the next version 0.4.0

### ISSUE THREAD

**Issue by chao2zhang** [detekt/sarif4k#63]
I am encountering https://github.com/gradle-nexus/publish-plugin/issues/208 when publishing this locally. Open an issue for the record.

**Comment by TWiStErRob** [comment]
Add the dependency manually as a workaround, there's no other way in 8.

**Comment by cortinico** [comment]
Had this same exact problem on another project:
- https://github.com/facebookincubator/dataclassgenerate/commit/bd557c7f932e0cde4b278d100c5b5bcea1be2832

**Comment by chao2zhang** [comment]
Closing this issue as there is a workaround

**Comment by TWiStErRob** [comment]
Do you want to commit the workaround?

**Comment by chao2zhang** [comment]
It's here https://github.com/detekt/sarif4k/blob/main/build.gradle.kts#L105
